function createfigure2(cdata1, cdata2,titleName)
%CREATEFIGURE2(cdata1, cdata2)
%  CDATA1:  image cdata
%  CDATA2:  image cdata

%  Auto-generated by MATLAB on 12-Apr-2018 17:01:24

% Create figure
figure1 = figure;
colormap(jet);

% Create subplot
subplot1 = subplot(1,2,1,'Parent',figure1);
axis off
hold(subplot1,'on');
axis square
% Create image
image(cdata1,'Parent',subplot1,'CDataMapping','scaled');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot1,[0.5 32.5]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot1,[0.5 32.5]);
box(subplot1,'on');
axis(subplot1,'ij');
% Set the remaining axes properties
set(subplot1,'Layer','top');
% Create subplot
subplot2 = subplot(1,2,2,'Parent',figure1);
axis off
hold(subplot2,'on');

% Create image
image(cdata2,'Parent',subplot2);
title(titleName)
% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot2,[0.5 32.5]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot2,[0.5 32.5]);
box(subplot2,'on');
axis(subplot2,'ij');
% Set the remaining axes properties
set(subplot2,'DataAspectRatio',[1 1 1],'Layer','top','TickDir','out');
